version: '3'

services:
  database:
    image: postgres
    container_name: pg_container
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=quotes
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: {}